project_id: 600485
pull_request_title: '[WIP] Do not merge'
pull_request_labels: ['Localization']
files:
  - source: /react/components/ErrorPage/messages/en.json
    translation: /%original_path%/%two_letters_code%.%file_extension%